[workspace]
resolver = "2"
members = [
    'moqt-core',
    'moqt-server',
    'moqt-server-sample',
    'moqt-client-sample',
    'moqt',
    'relay',
    'client',
    'integration-test',
    'gstreamer-client-sample/uni/sender',
    'gstreamer-client-sample/uni/receiver'
]
