[workspace]
resolver = "2"
members = [
    'moqt-core',
    'moqt-server',
    'moqt-server-sample',
    'moqt-client-wasm',
    'moqt-ingest-gateway',
    'moqt-client-rust',
    'moqt-client-onvif',
]
